### ISSUE TITLE
Slow/laggy redraw updates when focus is lost

### ISSUE THREAD

**Issue by nullun** [xunkar/llanfair#8]
Whilst running Llanfair and moving focus away from the window, the animations/fps absolutely plummet.

I have found online that you can revert back to Java 7's animations (assuming it's an issue/change with Java 8), but this doesn't seem like the "correct" solution.

Modify the Llanfair.sh/Llanfair.bat file to include `-Dsun.java2d.xrender=false` and the animations will update in the background.

System:
Debian GNU/Linux 9 (stretch)
Linux 4.9.0-2-amd64 x86_64

Java:
openjdk version "1.8.0_121"
OpenJDK Runtime Environment (build 1.8.0_121-8u121-b13-4-b13)
OpenJDK 64-Bit Server VM (build 25.121-b13, mixed mode)

**Comment by xunkar** [comment]
Thank you, that is indeed very troublesome, I need to investigate this. I suppose there is something new in JRE8 that allows any OS to save CPU time by lowering the refresh rate of background applications but this is a wild guess.

**Comment by GlitchCog** [comment]
This java gaming forum post describes this issue and its resolution:
[http://www.java-gaming.org/index.php?topic=19224.0](http://www.java-gaming.org/index.php?topic=19224.0)

It looks like it's specific to the Window Manager. I've confirmed that this bug exists on:
1) Ubuntu/Mate, and 
2) Gentoo/i3

I noticed that you have a SupportedOS enum that lists the operating system. If you know what OS is being used, it might be prudent to limit this sync call to the Toolkit to only operating systems that need it, but that would require figuring out which need it and which do not.

**Comment by GlitchCog** [comment]
Another Linux distro example case, the bug was **not** present in this environment:

3. Arch Linux/i3

In addition to my own environment, these other example cases were collected from Twitch users SleepyMario and AD2srl, both of whom use Llanfair in their streams.
